//	type AutoGenerated []struct {
//		Company string `json:"company"`
//		Address struct {
//			Street  string `json:"street"`
//			City    string `json:"city"`
//			State   string `json:"state"`
//			Zipcode string `json:"zipcode"`
//		} `json:"address"`
//		Departments []struct {
//			Name string `json:"name"`
//			Head struct {
//				Name     string `json:"name"`
//				Position string `json:"position"`
//			} `json:"head"`
//			Employees []struct {
//				ID       int      `json:"id"`
//				Name     string   `json:"name"`
//				Position string   `json:"position"`
//				Skills   []string `json:"skills"`
//			} `json:"employees"`
//			Projects []struct {
//				ProjectID   string   `json:"projectId"`
//				Name        string   `json:"name"`
//				Description string   `json:"description"`
//				Team        []string `json:"team"`
//				Status      string   `json:"status"`
//			} `json:"projects"`
//		} `json:"departments"`
//	}
package main
